ci: checkout branch for pushdiff action
Signed-off-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>

diff --git a/.github/actions/pushdiff/action.yml b/.github/actions/pushdiff/action.yml
--- a/.github/actions/pushdiff/action.yml
+++ b/.github/actions/pushdiff/action.yml
@@ -42,6 +42,10 @@ runs:
         (!github.event.pull_request.head.repo.fork)
       shell: bash
       run: |
+        if ! git status | grep -q "On branch"; then
+          echo "::error::pushdiff must run on a branch. Pass 'github.head_ref' as 'ref' to the checkout action."
+          exit 1
+        fi
         git config --global user.name "edgelessci"
         git config --global user.email "edgelessci@users.noreply.github.com"
         git commit -am "${{ inputs.renovate-commit-msg }}"
