ci: prevent merge of PRs with do-not-merge label
Co-authored-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>

diff --git a/.github/workflows/require_label.yml b/.github/workflows/require_label.yml
--- a/.github/workflows/require_label.yml
+++ b/.github/workflows/require_label.yml
@@ -22,3 +22,11 @@ jobs:
             feature
             documentation
             no changelog
+  do-not-merge:
+    if: ${{ contains(github.event.pull_request.labels.*.name, 'do not merge') }}
+    runs-on: ubuntu-22.04
+    steps:
+      - name: prevent merge
+        run: |
+          echo '::error::This PR is labeled as "do not merge", remove the label to make this check pass.'
+          exit 1
